import { Token } from "types/response"

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
]

export const tokens: Array<Token> = [
  {
    icon: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    name: "Bitcoin",
    symbol: "BTC",
    price: 97203.12,
    decimals: 8,
    percentChange: 2.3,
    address: "0x",
    balance: 0.39,
  },
  {
    icon: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    name: "Ethereum",
    symbol: "ETH",
    price: 3215.75,
    decimals: 18,
    percentChange: -1.2,
    address: "0x",
    balance: 1.25,
  },
  {
    icon: "https://cryptologos.cc/logos/tether-usdt-logo.png",
    name: "Tether",
    symbol: "USDT",
    price: 1.0,
    decimals: 6,
    percentChange: 0.1,
    address: "0x",
    balance: 100.0,
  },
  {
    icon: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
    name: "Binance Coin",
    symbol: "BNB",
    price: 418.25,
    decimals: 18,
    percentChange: 0.5,
    address: "0x",
    balance: 2.33,
  },
  {
    icon: "https://cryptologos.cc/logos/solana-sol-logo.png",
    name: "Solana",
    symbol: "SOL",
    price: 115.42,
    decimals: 9,
    percentChange: -3.8,
    address: "0x",
    balance: 14.8,
  },
]
